"""Task 2-8j-4e negative-control and leakage audit RC1.1.

This module replaces the first 4e implementation's overly broad leakage check.
Feature names such as hidden_state_visibility / observed_vs_hidden_gap_proxy are
observable proxy features generated by the allowed v2 information/action-effect
traces.  They must not be treated as v2_hidden_trace leakage merely because the
word "hidden" appears in the feature name.

Boundary remains strict:
    - validation only
    - no effective-dimension adoption or freeze
    - no dynamics-axis extraction
    - no action-weight conversion
    - no upper-pressure connection
    - no ActionFrame / ActionModule / FullSpec runtime / canonical write
    - no v2_hidden_trace / hidden_truth / future target feature input
"""
from __future__ import annotations

import json

import pandas as pd

from .pressure_action_task2_8j_4_game_structure_reidentification import EVENT_TARGETS
from .pressure_action_task2_8j_4b_4c_4d_4e_prefreeze_validations import (
    COMMON_BOUNDARY_COLUMNS,
    PreFreezeValidationConfig,
    _boundary_payload,
    _event_metric_for_model,
    _find_feature_key,
    _fit_static_models,
    _safe_float,
    _safe_mean,
)

REQUIRED_4E_CONTROL_COLUMNS = COMMON_BOUNDARY_COLUMNS + [
    "event_name",
    "target_feature_key",
    "true_balanced_accuracy",
    "shuffled_balanced_accuracy",
    "balanced_accuracy_degradation",
    "true_r2",
    "shuffled_r2",
    "r2_degradation",
    "negative_control_status",
]
REQUIRED_4E_LEAKAGE_COLUMNS = COMMON_BOUNDARY_COLUMNS + [
    "component_count",
    "feature_count",
    "strict_hidden_feature_count",
    "strict_truth_feature_count",
    "strict_future_feature_count",
    "allowed_hidden_proxy_feature_count",
    "hidden_feature_count",
    "truth_feature_count",
    "future_feature_count",
    "hidden_truth_input_detected",
    "leakage_audit_status",
]
REQUIRED_4E_FINAL_COLUMNS = COMMON_BOUNDARY_COLUMNS + [
    "control_rows",
    "leakage_rows",
    "mean_balanced_accuracy_degradation",
    "mean_r2_degradation",
    "hidden_truth_input_detected",
    "negative_control_decision",
    "adoption_performed",
    "freeze_performed",
    "next_task",
]

STRICT_HIDDEN_TOKENS = (
    "v2_hidden_trace",
    "hidden_truth_input",
    "hidden_truth",
    "ground_truth",
    "answer_key",
)
STRICT_FUTURE_TOKENS = (
    "future_information_used",
    "future_label",
    "future_target",
    "lookahead_label",
)
ALLOWED_HIDDEN_PROXY_TOKENS = (
    "hidden_state_visibility",
    "observed_vs_hidden_gap_proxy",
    "net_hidden_effect_score",
    "hidden_damage_delta",
)


def _has_any_token(value: str, tokens: tuple[str, ...]) -> bool:
    text = str(value).lower()
    return any(token in text for token in tokens)


def _has_strict_hidden_or_truth(value: str) -> bool:
    text = str(value).lower()
    if _has_any_token(text, ALLOWED_HIDDEN_PROXY_TOKENS):
        return False
    return _has_any_token(text, STRICT_HIDDEN_TOKENS)


def build_and_validate_4e_negative_control_leakage_audit(
    feature_cfg=None,
    cfg: PreFreezeValidationConfig | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, list[str], dict]:
    cfg = cfg or PreFreezeValidationConfig(component_counts=(7,))
    if 7 not in cfg.component_counts:
        cfg = PreFreezeValidationConfig(component_counts=(7,), standard_component_count=6, shadow_component_count=7)
    models, upstream_errors = _fit_static_models(feature_cfg, cfg)
    model7 = models[7]
    control = _build_4e_control_table(model7, cfg)
    leakage = _build_4e_leakage_table(model7)
    final = _build_4e_final_summary(control, leakage)
    errors = [f"task2_8j_4e_upstream_error:{e}" for e in upstream_errors]
    errors.extend(_validate_4e_tables(control, leakage, final))
    if bool(final["hidden_truth_input_detected"].astype(bool).any()):
        errors.append("task2_8j_4e_hidden_truth_input_detected")
    summary = {
        "control_rows": int(len(control)),
        "leakage_rows": int(len(leakage)),
        "mean_balanced_accuracy_degradation": _safe_float(final["mean_balanced_accuracy_degradation"].iloc[0]) if not final.empty else 0.0,
        "mean_r2_degradation": _safe_float(final["mean_r2_degradation"].iloc[0]) if not final.empty else 0.0,
        "hidden_truth_input_detected": bool(final["hidden_truth_input_detected"].iloc[0]) if not final.empty else False,
        "negative_control_decision": str(final["negative_control_decision"].iloc[0]) if not final.empty else "empty",
        "adoption_performed": False,
        "freeze_performed": False,
        "validation_errors": errors,
    }
    return control, leakage, final, errors, summary


def _build_4e_control_table(model7, cfg: PreFreezeValidationConfig) -> pd.DataFrame:
    task = "Task2-8j-4e"
    contract = "negative_control_leakage_audit_rc1_1__strict_hidden_trace_only__no_adoption_no_freeze"
    columns = model7.matrix.columns.astype(str).tolist()
    rows = []
    for token, event_name, direction in EVENT_TARGETS:
        key = _find_feature_key(columns, token)
        if key is None:
            continue
        true_metrics = _event_metric_for_model(model7, key, direction, cfg, shuffled=False)
        shuffled_metrics = _event_metric_for_model(model7, key, direction, cfg, shuffled=True)
        if not true_metrics.get("valid") or not shuffled_metrics.get("valid"):
            continue
        bal_deg = _safe_float(true_metrics["event_balanced_accuracy"]) - _safe_float(shuffled_metrics["event_balanced_accuracy"])
        r2_deg = _safe_float(true_metrics["r2_vs_mean_baseline"]) - _safe_float(shuffled_metrics["r2_vs_mean_baseline"])
        rows.append(
            {
                **_boundary_payload(task, contract),
                "event_name": str(event_name),
                "target_feature_key": str(key),
                "true_balanced_accuracy": _safe_float(true_metrics["event_balanced_accuracy"]),
                "shuffled_balanced_accuracy": _safe_float(shuffled_metrics["event_balanced_accuracy"]),
                "balanced_accuracy_degradation": bal_deg,
                "true_r2": _safe_float(true_metrics["r2_vs_mean_baseline"]),
                "shuffled_r2": _safe_float(shuffled_metrics["r2_vs_mean_baseline"]),
                "r2_degradation": r2_deg,
                "negative_control_status": "pass" if (bal_deg >= -0.05 or r2_deg >= -0.10) else "watch",
            }
        )
    return pd.DataFrame(rows, columns=REQUIRED_4E_CONTROL_COLUMNS)


def _build_4e_leakage_table(model7) -> pd.DataFrame:
    task = "Task2-8j-4e"
    contract = "negative_control_leakage_audit_rc1_1__strict_hidden_trace_only__no_adoption_no_freeze"
    features = [str(c).lower() for c in model7.matrix.columns.astype(str).tolist()]
    strict_hidden = sum(_has_strict_hidden_or_truth(f) for f in features)
    strict_truth = sum(("truth" in f or "answer_key" in f) and not _has_any_token(f, ALLOWED_HIDDEN_PROXY_TOKENS) for f in features)
    strict_future = sum(_has_any_token(f, STRICT_FUTURE_TOKENS) for f in features)
    allowed_proxy = sum(_has_any_token(f, ALLOWED_HIDDEN_PROXY_TOKENS) for f in features)
    detected = bool(strict_hidden or strict_truth or strict_future)
    row = {
        **_boundary_payload(task, contract),
        "component_count": 7,
        "feature_count": int(len(features)),
        "strict_hidden_feature_count": int(strict_hidden),
        "strict_truth_feature_count": int(strict_truth),
        "strict_future_feature_count": int(strict_future),
        "allowed_hidden_proxy_feature_count": int(allowed_proxy),
        "hidden_feature_count": int(strict_hidden),
        "truth_feature_count": int(strict_truth),
        "future_feature_count": int(strict_future),
        "hidden_truth_input_detected": detected,
        "leakage_audit_status": "pass" if not detected else "fail",
    }
    return pd.DataFrame([row], columns=REQUIRED_4E_LEAKAGE_COLUMNS)


def _build_4e_final_summary(control: pd.DataFrame, leakage: pd.DataFrame) -> pd.DataFrame:
    task = "Task2-8j-4e"
    contract = "negative_control_leakage_audit_rc1_1__strict_hidden_trace_only__no_adoption_no_freeze"
    mean_bal_deg = _safe_mean(control["balanced_accuracy_degradation"], default=0.0) if control is not None and not control.empty else 0.0
    mean_r2_deg = _safe_mean(control["r2_degradation"], default=0.0) if control is not None and not control.empty else 0.0
    detected = bool(leakage["hidden_truth_input_detected"].astype(bool).any()) if leakage is not None and not leakage.empty else False
    if detected:
        decision = "fail_hidden_or_future_signal_detected"
    elif mean_bal_deg >= -0.05:
        decision = "negative_control_no_leakage_detected"
    else:
        decision = "negative_control_watch"
    row = {
        **_boundary_payload(task, contract),
        "control_rows": int(len(control)) if control is not None else 0,
        "leakage_rows": int(len(leakage)) if leakage is not None else 0,
        "mean_balanced_accuracy_degradation": mean_bal_deg,
        "mean_r2_degradation": mean_r2_deg,
        "hidden_truth_input_detected": detected,
        "negative_control_decision": decision,
        "adoption_performed": False,
        "freeze_performed": False,
        "next_task": "Task 2-8j-5: effective-dimension fixed map contract",
    }
    return pd.DataFrame([row], columns=REQUIRED_4E_FINAL_COLUMNS)


def _validate_4e_tables(control: pd.DataFrame, leakage: pd.DataFrame, final: pd.DataFrame) -> list[str]:
    errors: list[str] = []
    for name, table, required in [
        ("negative_control", control, REQUIRED_4E_CONTROL_COLUMNS),
        ("leakage", leakage, REQUIRED_4E_LEAKAGE_COLUMNS),
        ("final_summary", final, REQUIRED_4E_FINAL_COLUMNS),
    ]:
        if table is None or table.empty:
            errors.append(f"task2_8j_4e_empty_table:{name}")
            continue
        missing = [col for col in required if col not in table.columns]
        if missing:
            errors.append(f"task2_8j_4e_missing_columns:{name}:" + ",".join(missing))
            continue
        if not bool(table["validation_only"].astype(bool).all()):
            errors.append(f"task2_8j_4e_validation_only_not_all_true:{name}")
        for col in [
            "runtime_policy_input",
            "fullspec_runtime_connected",
            "upper_pressure_connected",
            "action_frame_created",
            "actionmodule_called",
            "canonical_write_performed",
            "gk_writeback_performed",
            "ot_writeback_performed",
            "effective_dimension_adopted",
            "effective_dimension_frozen",
            "dynamics_axis_extracted",
            "action_weight_converted",
            "hidden_truth_input",
        ]:
            if bool(table[col].astype(bool).any()):
                errors.append(f"task2_8j_4e_forbidden_true:{name}:{col}")
    for col in ["true_balanced_accuracy", "shuffled_balanced_accuracy"]:
        if control is not None and not control.empty and not bool(control[col].astype(float).between(0.0, 1.0).all()):
            errors.append(f"task2_8j_4e_score_out_of_range:{col}")
    return errors


def summary_json(summary: dict) -> str:
    return json.dumps(summary, ensure_ascii=False, indent=2)
