"""Task 2-7b: insurance terrain gate closed validation RC1.

Validation goal:
    v2-style dangerous state
      -> lower observation terrain extraction
      -> upper pressure projection
      -> pressure-derived six-action candidates
      -> insurance terrain gate
      -> validation-local action result
      -> improvement / side-effect audit
      -> activation-threshold sweep

Anti-arbitrariness rules:
    - dangerous states are generated by deterministic scenario templates
    - lower observation reads the generated state features, not hand-picked actions
    - upper pressure is projected from observation fields with deterministic rules
    - action candidates are produced by Task 2-6 and gated by Task 2-7
    - the validator compares surfaced candidates against no_op baseline
    - no ActionFrame, ActionModule, world runtime, or canonical write is performed
"""
from __future__ import annotations

from dataclasses import dataclass
import json
from typing import Iterable

import pandas as pd

from .pressure_action_calibration_rc1 import (
    _probe_action_effect,
    _side_effect_burden,
    _synthetic_action_frame,
)
from .pressure_action_task2_7_insurance_terrain_gate import (
    InsuranceTerrainGateConfig,
    build_insurance_terrain_action_gate_table,
)


TASK2_7B_VALIDATION_VERSION = "insurance_terrain_closed_validation_rc1"
TASK2_7B_VALIDATION_CONTRACT = (
    "Task2_7b_v2_danger_state_to_lower_observation_to_upper_pressure_to_terrain_gate__"
    "threshold_sweep__validation_only__no_ActionFrame__no_ActionModule"
)

V2_SCENARIOS = (
    {
        "v2_state_id": "v2_boundary_instability_danger",
        "boundary_load": 0.92,
        "volatility": 0.86,
        "recovery_capacity": 0.18,
        "trend_deterioration": 0.78,
        "local_uncertainty": 0.64,
        "residual_noise": 0.55,
        "unresolved_mass": 0.50,
        "ambiguity": 0.42,
        "gain_potential": 0.10,
        "exploration_axis_gain": 0.12,
        "macro_gain": 0.08,
    },
    {
        "v2_state_id": "v2_unresolved_medium_danger",
        "boundary_load": 0.45,
        "volatility": 0.48,
        "recovery_capacity": 0.46,
        "trend_deterioration": 0.42,
        "local_uncertainty": 0.62,
        "residual_noise": 0.52,
        "unresolved_mass": 0.57,
        "ambiguity": 0.51,
        "gain_potential": 0.35,
        "exploration_axis_gain": 0.40,
        "macro_gain": 0.28,
    },
    {
        "v2_state_id": "v2_low_risk_gain_window",
        "boundary_load": 0.12,
        "volatility": 0.18,
        "recovery_capacity": 0.88,
        "trend_deterioration": 0.10,
        "local_uncertainty": 0.32,
        "residual_noise": 0.12,
        "unresolved_mass": 0.10,
        "ambiguity": 0.16,
        "gain_potential": 0.82,
        "exploration_axis_gain": 0.74,
        "macro_gain": 0.63,
    },
)

THRESHOLD_SWEEP = (
    {"threshold_profile": "conservative", "high_risk_threshold": 0.76, "medium_risk_threshold": 0.50, "safe_gain_risk_ceiling": 0.26, "safe_gain_threshold": 0.58},
    {"threshold_profile": "base", "high_risk_threshold": 0.68, "medium_risk_threshold": 0.42, "safe_gain_risk_ceiling": 0.32, "safe_gain_threshold": 0.50},
    {"threshold_profile": "reduced", "high_risk_threshold": 0.58, "medium_risk_threshold": 0.34, "safe_gain_risk_ceiling": 0.40, "safe_gain_threshold": 0.42},
)

REQUIRED_TASK2_7B_COLUMNS = [
    "task2_7b_validation_version",
    "task2_7b_validation_contract",
    "validation_type",
    "validation_only",
    "runtime_policy_input",
    "action_frame_created",
    "actionmodule_called",
    "world_runtime_called",
    "canonical_write_performed",
    "anti_arbitrariness_contract",
    "v2_state_id",
    "terrain_location_id",
    "threshold_profile",
    "high_risk_threshold",
    "medium_risk_threshold",
    "safe_gain_risk_ceiling",
    "safe_gain_threshold",
    "lower_observation_detected_risk",
    "lower_observation_risk_score",
    "lower_observation_gain_score",
    "upper_pressure_rows",
    "pressure_inputs_preserved",
    "gate_decision",
    "recommended_action_mode",
    "action_channel",
    "action_name_ja",
    "pressure_component",
    "component_direction",
    "pressure_strength",
    "terrain_risk_band",
    "terrain_risk_score",
    "terrain_gain_score",
    "recommended_action_strength_hint",
    "activated",
    "activation_rank",
    "no_op_risk_after",
    "action_risk_after",
    "risk_improvement_vs_no_op",
    "no_op_recovery_after",
    "action_recovery_after",
    "recovery_improvement_vs_no_op",
    "no_op_gain_after",
    "action_gain_after",
    "gain_improvement_vs_no_op",
    "side_effect_burden",
    "side_effect_delta_vs_no_op",
    "net_validation_benefit",
    "benefit_pass",
    "side_effect_guard_pass",
    "requires_local_audit_before_action",
    "requires_sandbox_before_action",
    "threshold_reduction_triggered_more_actions",
    "threshold_reduction_side_effect_caution",
    "validation_note",
]


@dataclass(frozen=True)
class ClosedValidationConfig:
    max_side_effect_burden: float = 0.20
    min_net_benefit: float = 0.005


def _clip01(value: float) -> float:
    return float(max(0.0, min(1.0, float(value))))


def _num(row: pd.Series | dict, key: str, default: float = 0.0) -> float:
    try:
        value = row.get(key, default)
        if pd.isna(value):
            return float(default)
        return float(value)
    except Exception:
        return float(default)


def build_v2_danger_states() -> pd.DataFrame:
    """Deterministic v2-style state templates for validation only."""
    rows = []
    for state in V2_SCENARIOS:
        row = dict(state)
        row["v2_state_contract"] = "deterministic_validation_template_not_runtime_world"
        row["validation_only"] = True
        row["runtime_policy_input"] = False
        rows.append(row)
    return pd.DataFrame(rows)


def lower_observation_from_v2_state(v2_states: pd.DataFrame) -> pd.DataFrame:
    """Extract terrain features from v2 state fields.

    This is a deterministic lower-observation projection.  It does not select an
    action and does not use upper pressure.
    """
    rows = []
    for _, s in v2_states.iterrows():
        rows.append({
            "terrain_location_id": str(s["v2_state_id"]),
            "v2_state_id": str(s["v2_state_id"]),
            "boundary_risk_score": _clip01(_num(s, "boundary_load")),
            "instability_score": _clip01(_num(s, "volatility")),
            "recovery_margin": _clip01(_num(s, "recovery_capacity")),
            "trend_risk_score": _clip01(_num(s, "trend_deterioration")),
            "local_uncertainty_score": _clip01(_num(s, "local_uncertainty")),
            "ot_residual_score": _clip01(_num(s, "residual_noise")),
            "ot_unresolved_score": _clip01(_num(s, "unresolved_mass")),
            "ot_ambiguity_score": _clip01(_num(s, "ambiguity")),
            "terrain_gain_potential_score": _clip01(_num(s, "gain_potential")),
            "exploration_axis_gain_score": _clip01(_num(s, "exploration_axis_gain")),
            "macro_trend_gain_score": _clip01(_num(s, "macro_gain")),
            "lower_observation_contract": "v2_state_features_to_terrain__no_action_selection__no_pressure_selection",
            "validation_only": True,
            "runtime_policy_input": False,
        })
    return pd.DataFrame(rows)


def upper_pressure_from_lower_observation(terrain: pd.DataFrame) -> pd.DataFrame:
    """Project upper pressure from lower observation without choosing actions.

    This keeps pressure generation deterministic and pressure-side.  The pressure
    rows are inputs to Task 2-6; they do not directly select action channels.
    """
    rows = []
    for _, t in terrain.iterrows():
        state_id = str(t["v2_state_id"])
        boundary = _num(t, "boundary_risk_score")
        instability = _num(t, "instability_score")
        recovery_deficit = 1.0 - _num(t, "recovery_margin")
        trend = _num(t, "trend_risk_score")
        uncertainty = _num(t, "local_uncertainty_score")
        unresolved = max(_num(t, "ot_residual_score"), _num(t, "ot_unresolved_score"), _num(t, "ot_ambiguity_score"))
        gain = max(_num(t, "terrain_gain_potential_score"), _num(t, "exploration_axis_gain_score"), _num(t, "macro_trend_gain_score"))

        projected = [
            ("rollback_sensitivity", "increase", 10.0 * _clip01(0.50 * recovery_deficit + 0.30 * boundary + 0.20 * instability)),
            ("pressure_cap", "decrease", 10.0 * _clip01(0.45 * boundary + 0.35 * instability + 0.20 * trend)),
            ("diagnostic_depth", "increase", 10.0 * _clip01(0.55 * unresolved + 0.35 * uncertainty + 0.10 * trend)),
            ("exploration_frequency", "increase", 10.0 * _clip01(0.55 * gain + 0.25 * uncertainty + 0.20 * (1.0 - boundary))),
            ("commitment_strength", "decrease", 10.0 * _clip01(0.40 * instability + 0.35 * unresolved + 0.25 * trend)),
        ]
        for component, direction, strength in projected:
            if strength <= 0.05:
                continue
            rows.append({
                "pressure_input_id": f"pressure_from_{state_id}_{component}_{direction}",
                "v2_state_id": state_id,
                "pressure_component": component,
                "component_direction": direction,
                "pressure_strength": float(strength),
                "upper_pressure_projection_contract": "deterministic_from_lower_observation__no_action_channel_selection",
                "validation_only": True,
                "runtime_policy_input": False,
            })
    return pd.DataFrame(rows)


def _state_band_from_risk(risk: float) -> str:
    if risk >= 0.78:
        return "limit"
    if risk >= 0.58:
        return "high"
    if risk >= 0.34:
        return "medium"
    return "stable"


def _simulate_action_result(row: pd.Series) -> dict:
    """Validation-local result model against no_op baseline.

    The response signature comes from the existing Task 2-2 validation probe. It
    is used here only to compare surfaced candidates to no_op, not as runtime.
    """
    risk = _num(row, "terrain_risk_score")
    gain = _num(row, "terrain_gain_score")
    recovery_base = max(0.0, 1.0 - risk)
    strength = _num(row, "recommended_action_strength_hint")
    state_band = _state_band_from_risk(risk)
    action = str(row["action_channel"])
    if not bool(row["activated"]):
        action = "no_op"
        strength = 0.0
    baseline = _probe_action_effect(_synthetic_action_frame(state_band, "no_op", 41, max(strength, 0.0)))
    effect = _probe_action_effect(_synthetic_action_frame(state_band, action, 41, max(strength, 0.0)))
    side_effect = _side_effect_burden(effect)
    baseline_side_effect = _side_effect_burden(baseline)

    # Improvement model is intentionally coarse: safety actions reduce risk and
    # improve recovery in dangerous terrain; safe-gain probes improve gain in low
    # risk terrain. Opening actions in dangerous terrain are not activated by the
    # insurance gate, so they usually collapse to no_op here.
    insurance_factor = 1.0 if str(row["recommended_action_mode"]) == "insurance" else 0.0
    safe_gain_factor = 1.0 if str(row["recommended_action_mode"]) == "safe_gain_probe" else 0.0
    audit_factor = 0.5 if str(row["recommended_action_mode"]) == "audit_before_action" else 0.0

    risk_reduction = _clip01(0.58 * strength * insurance_factor + 0.22 * strength * audit_factor + 0.10 * max(effect.get("reversibility_delta", 0.0), 0.0))
    recovery_gain = _clip01(0.62 * strength * insurance_factor + 0.18 * strength * audit_factor + 0.18 * max(effect.get("reversibility_delta", 0.0), 0.0))
    gain_improvement = _clip01(0.70 * strength * safe_gain_factor + 0.12 * max(effect.get("exploration_delta", 0.0), 0.0))

    no_op_risk_after = risk
    action_risk_after = _clip01(risk - risk_reduction)
    no_op_recovery_after = recovery_base
    action_recovery_after = _clip01(recovery_base + recovery_gain)
    no_op_gain_after = gain
    action_gain_after = _clip01(gain + gain_improvement)
    return {
        "no_op_risk_after": no_op_risk_after,
        "action_risk_after": action_risk_after,
        "risk_improvement_vs_no_op": float(no_op_risk_after - action_risk_after),
        "no_op_recovery_after": no_op_recovery_after,
        "action_recovery_after": action_recovery_after,
        "recovery_improvement_vs_no_op": float(action_recovery_after - no_op_recovery_after),
        "no_op_gain_after": no_op_gain_after,
        "action_gain_after": action_gain_after,
        "gain_improvement_vs_no_op": float(action_gain_after - no_op_gain_after),
        "side_effect_burden": float(side_effect),
        "side_effect_delta_vs_no_op": float(side_effect - baseline_side_effect),
    }


def _build_threshold_config(profile: dict) -> InsuranceTerrainGateConfig:
    return InsuranceTerrainGateConfig(
        high_risk_threshold=float(profile["high_risk_threshold"]),
        medium_risk_threshold=float(profile["medium_risk_threshold"]),
        safe_gain_risk_ceiling=float(profile["safe_gain_risk_ceiling"]),
        safe_gain_threshold=float(profile["safe_gain_threshold"]),
    )


def build_insurance_closed_validation_table(
    threshold_sweep: Iterable[dict] = THRESHOLD_SWEEP,
    config: ClosedValidationConfig = ClosedValidationConfig(),
) -> pd.DataFrame:
    v2_states = build_v2_danger_states()
    terrain = lower_observation_from_v2_state(v2_states)
    pressure = upper_pressure_from_lower_observation(terrain)

    all_rows = []
    profile_counts: dict[str, int] = {}
    profile_side_effects: dict[str, float] = {}
    for profile in threshold_sweep:
        threshold_profile = str(profile["threshold_profile"])
        gate = build_insurance_terrain_action_gate_table(
            pressure_inputs=pressure,
            terrain_map=terrain,
            config=_build_threshold_config(profile),
        )
        # Only compare pressure and terrain rows from the same v2 state. This
        # prevents a pressure generated from one state from being applied to a
        # different terrain location.
        gate = gate[gate["terrain_location_id"].astype(str).isin(gate["pressure_input_id"].astype(str).str.extract(r"pressure_from_(.*?)_(?:rollback|pressure|diagnostic|exploration|commitment)")[0].dropna().unique())] if False else gate
        gate = gate[gate.apply(lambda r: str(r["terrain_location_id"]) in str(r["pressure_input_id"]), axis=1)].copy()
        activated_mask = gate["gate_decision"].astype(str).isin({"surface_insurance_candidate", "surface_safe_gain_probe_candidate"})
        gate["activated"] = activated_mask
        gate = gate.sort_values(
            ["terrain_location_id", "activated", "terrain_risk_score", "safe_gain_opportunity_score", "insurance_need_score"],
            ascending=[True, False, False, False, False],
        ).reset_index(drop=True)
        gate["activation_rank"] = gate.groupby("terrain_location_id").cumcount() + 1

        for _, row in gate.iterrows():
            result = _simulate_action_result(row)
            net_benefit = (
                result["risk_improvement_vs_no_op"]
                + result["recovery_improvement_vs_no_op"]
                + result["gain_improvement_vs_no_op"]
                - result["side_effect_delta_vs_no_op"]
            )
            benefit_pass = bool(net_benefit >= config.min_net_benefit or not bool(row["activated"]))
            side_effect_guard = bool(result["side_effect_burden"] <= config.max_side_effect_burden or not bool(row["activated"]))
            all_rows.append({
                "task2_7b_validation_version": TASK2_7B_VALIDATION_VERSION,
                "task2_7b_validation_contract": TASK2_7B_VALIDATION_CONTRACT,
                "validation_type": "v2_danger_lower_observation_upper_pressure_insurance_gate_closed_validation",
                "validation_only": True,
                "runtime_policy_input": False,
                "action_frame_created": False,
                "actionmodule_called": False,
                "world_runtime_called": False,
                "canonical_write_performed": False,
                "anti_arbitrariness_contract": "state_templates_to_observation_to_pressure_to_gate__no_handpicked_action",
                "v2_state_id": str(row["terrain_location_id"]),
                "terrain_location_id": str(row["terrain_location_id"]),
                "threshold_profile": threshold_profile,
                "high_risk_threshold": float(profile["high_risk_threshold"]),
                "medium_risk_threshold": float(profile["medium_risk_threshold"]),
                "safe_gain_risk_ceiling": float(profile["safe_gain_risk_ceiling"]),
                "safe_gain_threshold": float(profile["safe_gain_threshold"]),
                "lower_observation_detected_risk": bool(_num(row, "terrain_risk_score") >= float(profile["medium_risk_threshold"])),
                "lower_observation_risk_score": _num(row, "terrain_risk_score"),
                "lower_observation_gain_score": _num(row, "terrain_gain_score"),
                "upper_pressure_rows": int(pressure[pressure["v2_state_id"].astype(str) == str(row["terrain_location_id"])].shape[0]),
                "pressure_inputs_preserved": True,
                "gate_decision": str(row["gate_decision"]),
                "recommended_action_mode": str(row["recommended_action_mode"]),
                "action_channel": str(row["action_channel"]),
                "action_name_ja": str(row["action_name_ja"]),
                "pressure_component": str(row["pressure_component"]),
                "component_direction": str(row["component_direction"]),
                "pressure_strength": _num(row, "pressure_strength"),
                "terrain_risk_band": str(row["terrain_risk_band"]),
                "terrain_risk_score": _num(row, "terrain_risk_score"),
                "terrain_gain_score": _num(row, "terrain_gain_score"),
                "recommended_action_strength_hint": _num(row, "recommended_action_strength_hint"),
                "activated": bool(row["activated"]),
                "activation_rank": int(row["activation_rank"]),
                **result,
                "net_validation_benefit": float(net_benefit),
                "benefit_pass": benefit_pass,
                "side_effect_guard_pass": side_effect_guard,
                "requires_local_audit_before_action": bool(row["requires_local_audit_before_action"]),
                "requires_sandbox_before_action": bool(row["requires_sandbox_before_action"]),
                "threshold_reduction_triggered_more_actions": False,
                "threshold_reduction_side_effect_caution": False,
                "validation_note": str(row["terrain_gate_audit_note"]),
            })
        profile_counts[threshold_profile] = int(activated_mask.sum())
        profile_side_effects[threshold_profile] = float(gate.loc[activated_mask, "recommended_action_strength_hint"].sum()) if activated_mask.any() else 0.0

    out = pd.DataFrame(all_rows)
    if out.empty:
        return pd.DataFrame(columns=REQUIRED_TASK2_7B_COLUMNS)

    base_count = profile_counts.get("base", 0)
    reduced_count = profile_counts.get("reduced", 0)
    conservative_count = profile_counts.get("conservative", 0)
    more_actions = bool(reduced_count > base_count >= conservative_count)
    base_side_proxy = profile_side_effects.get("base", 0.0)
    reduced_side_proxy = profile_side_effects.get("reduced", 0.0)
    side_caution = bool(reduced_side_proxy > base_side_proxy)
    out["threshold_reduction_triggered_more_actions"] = more_actions
    out["threshold_reduction_side_effect_caution"] = side_caution
    return out[REQUIRED_TASK2_7B_COLUMNS]


def summarize_insurance_closed_validation(table: pd.DataFrame) -> dict:
    if table is None or table.empty:
        return {"rows": 0}
    activated = table[table["activated"].astype(bool)].copy()
    by_profile = table.groupby("threshold_profile").agg(
        rows=("threshold_profile", "size"),
        activated_rows=("activated", lambda s: int(s.astype(bool).sum())),
        mean_net_benefit=("net_validation_benefit", "mean"),
        mean_side_effect=("side_effect_burden", "mean"),
        local_audit_rows=("requires_local_audit_before_action", lambda s: int(s.astype(bool).sum())),
        sandbox_rows=("requires_sandbox_before_action", lambda s: int(s.astype(bool).sum())),
    ).reset_index()
    return {
        "rows": int(len(table)),
        "v2_states": int(table["v2_state_id"].nunique()),
        "threshold_profiles": sorted(table["threshold_profile"].astype(str).unique().tolist()),
        "activated_rows": int(len(activated)),
        "mean_activated_net_benefit": float(activated["net_validation_benefit"].mean()) if not activated.empty else 0.0,
        "max_activated_side_effect_burden": float(activated["side_effect_burden"].max()) if not activated.empty else 0.0,
        "threshold_reduction_triggered_more_actions": bool(table["threshold_reduction_triggered_more_actions"].astype(bool).any()),
        "threshold_reduction_side_effect_caution": bool(table["threshold_reduction_side_effect_caution"].astype(bool).any()),
        "by_threshold_profile": by_profile.to_dict(orient="records"),
    }


def validate_insurance_closed_validation_table(table: pd.DataFrame) -> list[str]:
    errors: list[str] = []
    if table is None or table.empty:
        return ["task2_7b_closed_validation_table_empty"]
    missing = sorted(set(REQUIRED_TASK2_7B_COLUMNS) - set(table.columns))
    if missing:
        errors.append("task2_7b_required_columns_missing:" + ",".join(missing))
        return errors

    false_fields = ["runtime_policy_input", "action_frame_created", "actionmodule_called", "world_runtime_called", "canonical_write_performed"]
    for field in false_fields:
        if bool(table[field].astype(bool).any()):
            errors.append(f"task2_7b_forbidden_true_field:{field}")

    if not bool(table["validation_only"].astype(bool).all()):
        errors.append("task2_7b_validation_only_not_all_true")
    if not bool(table["pressure_inputs_preserved"].astype(bool).all()):
        errors.append("task2_7b_pressure_inputs_not_preserved")

    for col in [
        "lower_observation_risk_score", "lower_observation_gain_score", "terrain_risk_score",
        "terrain_gain_score", "recommended_action_strength_hint", "side_effect_burden",
        "side_effect_delta_vs_no_op",
    ]:
        vals = pd.to_numeric(table[col], errors="coerce")
        if bool(vals.isna().any() or (vals < 0.0).any()):
            errors.append(f"task2_7b_invalid_nonnegative_score:{col}")

    danger = table[table["v2_state_id"].astype(str).isin(["v2_boundary_instability_danger", "v2_unresolved_medium_danger"])]
    if danger.empty or not bool(danger["lower_observation_detected_risk"].astype(bool).any()):
        errors.append("task2_7b_lower_observation_failed_to_detect_danger")

    activated = table[table["activated"].astype(bool)]
    if activated.empty:
        errors.append("task2_7b_no_actions_activated")
    elif not bool((activated["net_validation_benefit"] > 0.0).any()):
        errors.append("task2_7b_no_positive_net_benefit_activated_action")

    if not bool(table["threshold_reduction_triggered_more_actions"].astype(bool).any()):
        errors.append("task2_7b_threshold_reduction_did_not_trigger_more_actions")

    return errors


def build_and_validate_insurance_closed_validation_table() -> tuple[pd.DataFrame, list[str], dict]:
    table = build_insurance_closed_validation_table()
    errors = validate_insurance_closed_validation_table(table)
    summary = summarize_insurance_closed_validation(table)
    return table, errors, summary
